task:
    name: FFHQ
    id: '001'

net:
    z_dim: 512
    max_channels: 512
    max_size: 128
    preG_path: null
    preD_path: null

dataset:
    name: 'FFHQDataset'
    data_dir: '/data1/cgl/dataset/face/seeprettyface_yellow_face_128/thumbnails128x128'
    num_dataset: 60000
    noise_mean: 0
    noise_std: 1
    fixed_z_path: null
    
train:
    device: 'cuda:0'
    lr: 0.001
    batch_n: 16
    epoches: 200
    current_step: 0
    current_epoch: 0
    save_every_epoches: 50
    
output:
    output_dir: '/data1/cgl/tasks'

